env:
  global:
    - CC_TEST_REPORTER_ID=bb96c1ff9dc66724c38fb4eb54486dd72dc88a7fd6e727c034b9cf8d747d069e

language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - gem install rubocop

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rubocop
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
